# Site settings
title: Overripe for Disruption
# email: 
description: > # this means to ignore newlines until "baseurl:"
  Banter as a Service
baseurl:  # the subpath of your site, e.g. /blog/
url: http://aschuster3.github.io
# twitter_username: twitter_username
# github_username:  github_username

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: true
    permalink: /poetry/:path/


